# Generated by Django 4.2.1 on 2023-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesisChemical',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precursor_chemicals', models.JSONField()),
                ('synthesized_by', models.CharField(max_length=200)),
                ('synthesized_on', models.DateField()),
                ('added_by', models.CharField(max_length=200)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
