# Generated by Django 4.2.1 on 2023-06-14 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0004_synthesischemical_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesischemical',
            name='custom_parameters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
