# Generated by Django 4.2.1 on 2023-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0005_synthesischemical_custom_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesischemical',
            name='additional_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
