field_type = {
    'Metal_oxides': {
        'Other names': 'string',
        'Purity': 'string',
        'CAS number': 'string',
        'Chemical formula': 'string',
        'Batch number': 'string',
        'MSDS': 'file',
        'URL': 'url',
        'Location': 'string',
        'Purchased on': 'datetime',
        'Purchased by': 'string',
    },
    'Metal_salts': {
        'Other names': 'string',
        'Purity': 'string',
        'CAS number': 'string',
        'Chemical formula': 'string',
        'Batch number': 'string',
        'MSDS': 'file',
        'URL': 'url',
        'Location': 'string',
        'Purchased on': 'datetime',
        'Purchased by': 'string',
    },
    'Pure_gas': {
        'Other names': 'string',
        'Purity': 'string',
        'CAS number': 'string',
        'Chemical formula': 'string',
        'Batch number': 'string',
        'MSDS': 'file',
        'URL': 'url',
        'Location': 'string',
        'Purchased on': 'datetime',
        'Purchased by': 'string',
    },
    'Gas_mixture': {
        'Other names': 'string',
        'Purity': 'string',
        'CAS number': 'string',
        'Chemical formula': 'string',
        'Batch number': 'string',
        'MSDS': 'file',
        'URL': 'url',
        'Location': 'string',
        'Purchased on': 'datetime',
        'Purchased by': 'string',
    },
}
   